firewall: omit the port field for the icmp
Currently "compute firewall list" shows following for a rule using icmp

... protocol:icmp,ports:0,address:0.0.0.0/0,address:::/0 ...

Problem is using this syntax ends up with an error.

```
$ doctl compute firewall create --name test --outbound-rules "protocol:icmp,ports:all,address:0.0.0.0/0,address:::/0"
...
Error: POST https://api.digitalocean.com/v2/firewalls: 422 (request UUID) You must specify a positive value for ports.
```

whereas omitting the port field works as expected.

```
$ doctl compute firewall create --name test --outbound-rules "protocol:icmp,address:0.0.0.0/0,address:::/0"
ID                                      Name    Status     Created At              Inbound Rules    Outbound Rules                                          Droplet IDs    Tags          Pending Changes
...
```

so this change omits the ports field from the "compute firewall list" output.